---
title: "Wolves in the West: A Longitudinal Analysis of Wolf Depredations on Cattle"
shorttitle: "Wolves in the West"
abstract: A super great abstract
keywords: [wolves, cattle]
thanks: Thanks to everyone for checking this out.
reference-section-title: References
bibliography: ../bibliography/project.bib
csl: ../bibliography/chicago-parenthetical.csl
format:
  pdf:
    keep-tex: false
    include-in-header: 
      text: |
        \usepackage{dcolumn}
#  submittable-pdf:
#     keep-tex: false
#     fig-pos: "!t"
#     include-in-header: 
#       text: |
#         \usepackage{dcolumn}
  submittable-docx: default
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

# Introduction

The reintroduction of wolves in the continental United States is often heralded as a conservation success story [Beggen 2019]. Wolves had been essentially eliminated in the lower 48 states by the mid-1900s, but the passage of the Endangered Species Act (ESA) paved the way for wolf reintroduction. In 1995 and 1996 wolves were translocated from Canada and released in Yellowstone National Park and the Sawtooth National Forest in Idaho. Over the proceeding decades wolf populations have risen, and this increase in population is matched with a rising contentiousness. The ranching community has been an outspoken voice challenging the conservation of wolves and their fraught position as an protected species. Ranchers cite the economic costs of wolf depredation on cattle as a cause for their concerns, yet current data shows that wolves only account for a very small minority of cattle loss. 

In 2017, the United States Department of Agriculture (USDA) published a comprehensive report of all cattle and calf mortalities for the year 2015 [USDA 2017]. This publication details reported causes of predatory and non-predatory loss of cattle, including wolf depredation. Two years later, the Humane Society of the United States (HSUS) published a report relying heavily on the aforementioned USDA data The HSUS report clearly demonstrates that the amount of cattle lost to wolves is minuscule compared to other causes of death and the cattle population overall [HSUS 2019]. However, the study area included the entire United States, much of which has no wolf population, thus deflating the percentage of wolf depredations. The data used for the report was also from just one year and does not give an idea of how wolf depredation changes over time. 

If wolves are such a pressing economic issue for ranchers in the United States, why is there no place based longitudinal analysis of the issue? Are economic costs the true issue at hand, or are finances taking the blame for a deeper matter? 

In this study I conduct a longitudinal analysis of the relationship between wolf population, cattle population and wolf depredation in the Western United States. For the purpose of the research the "Western" United States will include: Washington, Oregon, Montana and Wyoming. All of these states have ranching operations and wolf populations that can trace their lineage to the original relocated wolves in the mid-90s.

# Data and Methods

The variables in question for this research are cattle population, cattle mortality, wolf population, and confirmed wolf kills for cattle. These variables are organized by state and year starting from 2012 and ending at 2022. I downloaded data on cattle population and mortality by state and year through the USDA Quickfacts database. Two issues arise when considering the USDA cattle data. First, the numbers for population and mortalities are all very evenly rounded indicating estimation on the part of the USDA. Secondly, not all of the cattle in the dataset are on range. Cattle grazing on range land are at greater risk for depredation than cattle living on feedlots. Cattle counted in the USDA datasets include adults and calves. 

I compiled the wolf data set myself by reading through annual wolf reports published by each state's respective Fish and Wildlife agency. I combed through annual reports and gleaned the wolf population per year and the number of cattle mortalities confirmed by the state to have been caused by wolves. The issue of reporting gets complicated across state lines and agencies. Some state reports have differing designations for "possible", "probable" and "confirmed" wolf kills. For the sake of consistency I only counted confirmed wolf kills for this report. In 2020 Wyoming changed it's reporting practices and lumped in injured and killed cattle into one value, so I opted to drop the wolf depredation values in Wyoming starting in 2020. Montana has not yet published their 2022 wolf report, so those values are unavailable in my data set. 

I originally intended to conduct this analysis with two additional states, Idaho and California. However, I encountered issues with a lack of data accessibility. Idaho has not published a wolf report for the public since 2016 and that is the only wolf report available on their Fish and Wildlife webpage. Without the help of a legal team I cannot pursue a FOIA request for that information so I made the tough decision to cut Idaho from this analysis, despite it's importance in wolf conservation and policy. California, on the other hand, publishes wolf reports quarterly that are difficult to glean yearlong information from. Given the difficulties of obtaining reliable annual information from Californian reports I made another tough decision to cut California from this report. 

All of the data for this report was collected in May 2023. 

# Results

After cleaning and organizing my data, I constructed 4 scatterplots for four variables: the cattle population by state,the total number of cattle mortalities per state, the wolf population per state, and the total number of confirmed wolf depredations on cattle per state. The scatterplots can be viewed below in figure 1, 2 3 and 4. 

Figure 1 demonstrates the sheer number of cattle housed within each state, with Montana far outranking Oregon, Wyoming and Washington. As mentioned previously, the USDA data does not differentiate between cattle on range and cattle confined within feedlots. Given this detail, this dataset does not accurately demonstrate how many cattle are at risk from wolf depredation. However, it does show how economically important cattle are for these states, and shows economic trends. Wyoming, Oregon, and Washington, all toward the bottom of the scatterplot, have similar cattle populations that have not fluctuated greatly since 2012. Montana, however, has seen a marked decline in cattle numbers since 2017. 

Figure 2 details the total mortalities for cattle in each state. This dataset does not differentiate between kinds of mortality, so it does not give a full scope of the reported causes of death. Given the 2015 data published by the USDA, we can hypothesize that the majority of deaths were caused by respiratory issues, however, we do not have the exact numbers. According to the USDA report, in 2015 98% of all deaths in adult cattle were non-predator related, with respiratory effects claiming 23.9% [USDA 2017]. 89% of all calf deaths in 2015 were attributed to non-predator causes, with respiratory issues again claiming the most lives at 26.9%. In Figure 2, Oregon appears to show the least variance, with an increase in 2019 that returned to a stable line. Montana, Wyoming and Washington showed more variance in the distribution of their data points.

Figure 3 is a linear model that draws a line of best fit for each state that helps to determine mortality trends. This addition shows that Wyoming and Washington also have fairly stable mortality trends without much change. Montana shows an upward trend in cattle mortality. 

Figure 4 displays the wolf population for each state. Toward the bottom of the scatterplot, Oregon and Washington have very similar values with upward trends. The wolf population for Washington and Oregon effectively double over the decade covered in the figure. Wyoming, despite some missing values, stays fairly stable and the wolf population does not rise above 300 individuals and dips below 250 individuals once in 2014-- before the two year data gap where their population recovers. Montana, again, is at the top of the scatterplot with a wolf population consistently over 1000 individuals. However, the wolf population reporting system in Montana is contentious. Washington, Oregon and Wyoming physically count wolf populations in the wild using traditional methods, while Montana solely uses a statistical model, iPOM, to track wolf populations in the state. This practice has come under fire for it's secrecy, efficacy and implications in liberalizing the hunting of wolves (Treves 2021). Aside from the population estimate controversy, I hypothesize that Montana has the highest wolf and cattle populations (and thus highest cattle mortalities) because of that state's large size. 

Figure 5 shows confirmed wolf depredations of cattle for each state. Wyoming has the most erratic data in the scatterplot. Most depredations in Wyoming fall between 30-60 instances per year, but there is one sizable outlier in 2017 with 113 confirmed cattle deaths. Montana, Oregon and Washington are all experiencing an increase in wolf depredation events, with Oregon seeing a marked increase starting in 2019. Washington stays fairly stable, with depredations never increasing over 15 instances. Montana has more variation with a distinct increase in depredation starting in 2014. 

Despite these increases in depredation events, it is crucial to note the scale between figures. There is a 3 log difference between the y-axis values of figure 2 and figure 5. The number of overall cattle deaths is counted in the tens of thousands, while the highest wolf depredation year of this study was 113 cases-- an single unusually high outlier. The average total cattle loss per year for each state over the 10 year period is 38500 cattle and calves. The average number of confirmed wolf depredations per year for each state over the same 10 years is 31. Cattle, on average, had a 0.08% chance of being confirmed to have been killed by a wolf in these states over the last decade. 

Figure 6 displays a linear model depicting the increased confirmed depredation events between all 4 states over the decade. (talk about the slope-- how much on an increase per year)

Figure 7 showcases another linear model of wolf population across Oregon, Montana, Washington and Wyoming. This line of best fit indicates that between these four states the wolf population is at a fairly stable trajectory. (talk about the slope)

Table 1 


# Conclusions
